import datetime

order_list = []
food_list_json = [
    {'Id': '27785', 'VendorName': '小昱咖啡', 'Name': '蘿蔔糕加蛋', 'Meal': 'A', 'Price': 35, 'Qty': 35, 'Location': '瑞昱一廠',
     'OrderCount': '5', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None, 'AddUser': None,
     'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27786', 'VendorName': '小昱咖啡', 'Name': '豬排蛋饅頭', 'Meal': 'A', 'Price': 40, 'Qty': 35, 'Location': '瑞昱一廠',
     'OrderCount': '1', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None, 'AddUser': None,
     'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27948', 'VendorName': '(A)自助餐-偉珍', 'Name': '沙茶烤雞腿', 'Meal': 'B', 'Price': 75, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '6', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': '新餐上市'},
    {'Id': '27983', 'VendorName': '(B)自助餐-國輝', 'Name': '香烤無骨雞腿肉', 'Meal': 'B', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '15', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27796', 'VendorName': '小昱咖啡', 'Name': '高麗菜水餃10顆+飲料', 'Meal': 'B', 'Price': 65, 'Qty': 50,
     'Location': '瑞昱一廠', 'OrderCount': '1', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27797', 'VendorName': '小昱咖啡', 'Name': '韮菜水餃10顆+飲料', 'Meal': 'B', 'Price': 65, 'Qty': 20, 'Location': '瑞昱一廠',
     'OrderCount': '', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None, 'AddUser': None,
     'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27798', 'VendorName': '小昱咖啡', 'Name': '打拋豬肉飯', 'Meal': 'B', 'Price': 80, 'Qty': 40, 'Location': '瑞昱一廠',
     'OrderCount': '5', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None, 'AddUser': None,
     'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27836', 'VendorName': '五花馬水餃館', 'Name': '榨菜肉絲乾麵(附湯)', 'Meal': 'B', 'Price': 70, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '3', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27837', 'VendorName': '五花馬水餃館', 'Name': '溫州大雲吞乾麵(附湯)', 'Meal': 'B', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '7', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27838', 'VendorName': '五花馬水餃館', 'Name': '酸辣麵(附小菜)', 'Meal': 'B', 'Price': 75, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '2', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27839', 'VendorName': '五花馬水餃館', 'Name': '高麗菜水餃(附湯)', 'Meal': 'B', 'Price': 65, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '7', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27840', 'VendorName': '五花馬水餃館', 'Name': '韭菜水餃(附湯)', 'Meal': 'B', 'Price': 65, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '1', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27841', 'VendorName': '五花馬水餃館', 'Name': '沙嗲水餃(附湯)', 'Meal': 'B', 'Price': 80, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '11', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27910', 'VendorName': '台灣小吃-饕爺', 'Name': '客家炒粄條套餐(附湯、小菜)', 'Meal': 'B', 'Price': 85, 'Qty': 200,
     'Location': '瑞昱一廠', 'OrderCount': '14', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27911', 'VendorName': '台灣小吃-饕爺', 'Name': '鍋燒意麵+日式豬排', 'Meal': 'B', 'Price': 85, 'Qty': 200,
     'Location': '瑞昱一廠', 'OrderCount': '19', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27890', 'VendorName': '吉利水果', 'Name': '綜合水果餐盒\n（內容：綜合水果、麵包）', 'Meal': 'B', 'Price': 65, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '6', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27891', 'VendorName': '吉利水果', 'Name': '綜合水果餐盒\n（內容：綜合水果）', 'Meal': 'B', 'Price': 65, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '12', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27995', 'VendorName': '快餐-聖珍', 'Name': '鹹酥雞丁飯', 'Meal': 'B', 'Price': 65, 'Qty': 999999, 'Location': '瑞昱一廠',
     'OrderCount': '4', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None, 'AddUser': None,
     'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27996', 'VendorName': '快餐-聖珍', 'Name': '黑咖哩豬排飯', 'Meal': 'B', 'Price': 75, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '6', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27997', 'VendorName': '快餐-聖珍', 'Name': '鹽蔥燒豚肉片飯', 'Meal': 'B', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '22', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': '新餐上市'},
    {'Id': '27973', 'VendorName': '風味餐-國輝', 'Name': '日式咖哩醬豬排', 'Meal': 'B', 'Price': 75, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '12', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27959', 'VendorName': '異國料理-偉珍', 'Name': '泰式打拋豬肉飯', 'Meal': 'B', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '33', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27960', 'VendorName': '異國料理-偉珍', 'Name': '日式雞肉炊飯', 'Meal': 'B', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '16', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27930', 'VendorName': '蓮華素食', 'Name': '香菇油飯組合餐', 'Meal': 'B', 'Price': 75, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '18', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27931', 'VendorName': '蓮華素食', 'Name': '胚芽便當', 'Meal': 'B', 'Price': 65, 'Qty': 999999, 'Location': '瑞昱一廠',
     'OrderCount': '1', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None, 'AddUser': None,
     'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '28039', 'VendorName': '燒臘-饕爺', 'Name': '油雞+香腸', 'Meal': 'B', 'Price': 85, 'Qty': 120, 'Location': '瑞昱一廠',
     'OrderCount': '120', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None,
     'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '28040', 'VendorName': '燒臘-饕爺', 'Name': '照燒里肌肉', 'Meal': 'B', 'Price': 85, 'Qty': 200, 'Location': '瑞昱一廠',
     'OrderCount': '148', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None,
     'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '28019', 'VendorName': '鍋類-聖珍', 'Name': '枸杞山藥雞湯鍋(附白飯)', 'Meal': 'B', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '7', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '28020', 'VendorName': '鍋類-聖珍', 'Name': '枸杞山藥雞湯鍋(附冬粉)', 'Meal': 'B', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27953', 'VendorName': '(A)自助餐-偉珍', 'Name': '蒜香烤排骨', 'Meal': 'C', 'Price': 75, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '11', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27988', 'VendorName': '(B)自助餐-國輝', 'Name': '宮保雞丁', 'Meal': 'C', 'Price': 65, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '2', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27811', 'VendorName': '小昱咖啡', 'Name': '高麗菜水餃10顆+飲料', 'Meal': 'C', 'Price': 65, 'Qty': 50,
     'Location': '瑞昱一廠', 'OrderCount': '', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27812', 'VendorName': '小昱咖啡', 'Name': '韮菜水餃10顆+飲料', 'Meal': 'C', 'Price': 65, 'Qty': 20, 'Location': '瑞昱一廠',
     'OrderCount': '1', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None, 'AddUser': None,
     'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27813', 'VendorName': '小昱咖啡', 'Name': '咖哩豬肉飯', 'Meal': 'C', 'Price': 80, 'Qty': 40, 'Location': '瑞昱一廠',
     'OrderCount': '6', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None, 'AddUser': None,
     'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27842', 'VendorName': '五花馬水餃館', 'Name': '京醬肉絲乾麵(附湯)', 'Meal': 'C', 'Price': 75, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '6', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27843', 'VendorName': '五花馬水餃館', 'Name': '醡醬乾麵(附湯)', 'Meal': 'C', 'Price': 75, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '4', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27844', 'VendorName': '五花馬水餃館', 'Name': '酸辣湯餃(附小菜)', 'Meal': 'C', 'Price': 80, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '8', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27845', 'VendorName': '五花馬水餃館', 'Name': '港式蘿蔔糕', 'Meal': 'C', 'Price': 60, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '30', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27846', 'VendorName': '五花馬水餃館', 'Name': '高麗菜水餃(附湯)', 'Meal': 'C', 'Price': 65, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '4', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27847', 'VendorName': '五花馬水餃館', 'Name': '韭菜水餃(附湯)', 'Meal': 'C', 'Price': 65, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '6', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27848', 'VendorName': '五花馬水餃館', 'Name': '虱目魚水餃(附湯)', 'Meal': 'C', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '7', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27920', 'VendorName': '台灣小吃-饕爺', 'Name': '滷肉飯套餐(附湯)', 'Meal': 'C', 'Price': 65, 'Qty': 200,
     'Location': '瑞昱一廠', 'OrderCount': '18', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27921', 'VendorName': '台灣小吃-饕爺', 'Name': '蚵仔麵線套餐(附泡菜臭豆腐)', 'Meal': 'C', 'Price': 85, 'Qty': 200,
     'Location': '瑞昱一廠', 'OrderCount': '27', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27900', 'VendorName': '吉利水果', 'Name': '綜合水果餐盒\n（內容：綜合水果、麵包）', 'Meal': 'C', 'Price': 65, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '20', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27901', 'VendorName': '吉利水果', 'Name': '綜合水果餐盒\n（內容：綜合水果）', 'Meal': 'C', 'Price': 65, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '34', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '28009', 'VendorName': '快餐-聖珍', 'Name': '紅槽肉飯', 'Meal': 'C', 'Price': 65, 'Qty': 999999, 'Location': '瑞昱一廠',
     'OrderCount': '', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None, 'AddUser': None,
     'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '28010', 'VendorName': '快餐-聖珍', 'Name': '南蠻炸雞排佐塔塔醬', 'Meal': 'C', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '12', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27978', 'VendorName': '風味餐-國輝', 'Name': '日式炒飯+照燒豬排', 'Meal': 'C', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '18', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27968', 'VendorName': '異國料理-偉珍', 'Name': '泰式綠咖哩牛肉飯', 'Meal': 'C', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '14', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27940', 'VendorName': '蓮華素食', 'Name': '紫米便當', 'Meal': 'C', 'Price': 65, 'Qty': 999999, 'Location': '瑞昱一廠',
     'OrderCount': '6', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None, 'AddUser': None,
     'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '27941', 'VendorName': '蓮華素食', 'Name': '炒泡麵加小菜附湯', 'Meal': 'C', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '4', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '28049', 'VendorName': '燒臘-饕爺', 'Name': '油雞+燒肉', 'Meal': 'C', 'Price': 85, 'Qty': 120, 'Location': '瑞昱一廠',
     'OrderCount': '120', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None,
     'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '28050', 'VendorName': '燒臘-饕爺', 'Name': '三杯雞肉飯', 'Meal': 'C', 'Price': 85, 'Qty': 200, 'Location': '瑞昱一廠',
     'OrderCount': '52', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None, 'AddDate': None,
     'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '28029', 'VendorName': '鍋類-聖珍', 'Name': '原味海鮮鍋(附白飯)', 'Meal': 'C', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '5', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''},
    {'Id': '28030', 'VendorName': '鍋類-聖珍', 'Name': '原味海鮮鍋(附意麵)', 'Meal': 'C', 'Price': 85, 'Qty': 999999,
     'Location': '瑞昱一廠', 'OrderCount': '2', 'Notice': None, 'EffectiveDate': '2022/11/15', 'Status': None,
     'AddDate': None, 'AddUser': None, 'ModDate': None, 'ModUser': None, 'Remark': ''}]
for item in food_list_json:
    if item["VendorName"] == "燒臘-饕爺" and item["Meal"] != "A":
        if "油雞" in item["Name"] or "香腸" in item["Name"] or "叉燒" in item["Name"] or "烤鴨" in item["Name"] or "大排" in item[
            "Name"]:
            order_list.append(item)

print(order_list)

order_list_post_format_data = []
for item in order_list:
    arrive_time_id = "4" if item["Meal"] == "B" else "5"
    data = {
        "Date": item["EffectiveDate"],
        "Meal": item["Meal"],
        "MealId": item["Id"],
        "Location": item["Location"],
        "FloorId": "6",
        "ArriveTimeId": arrive_time_id,
        "Count": "1",
        "MealName": item["Name"],
        "Money": item["Price"]
    }
    order_list_post_format_data.append(data)

